create table if not exists public.bot_users (
  telegram_id text primary key,
  microsoft jsonb,
  google jsonb,
  water_rule jsonb,
  bot_state jsonb,
  notification_state jsonb,
  last_sync_at timestamptz
);

alter table public.bot_users add column if not exists google jsonb;
alter table public.bot_users add column if not exists bot_state jsonb;
alter table public.bot_users add column if not exists notification_state jsonb;
alter table public.bot_users disable row level security;

create table if not exists public.news_sources (
  id bigint generated by default as identity primary key,
  telegram_id text not null references public.bot_users (telegram_id) on delete cascade,
  url text not null,
  channel_slug text not null,
  title text,
  last_post_id bigint,
  last_checked_at timestamptz,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  unique (telegram_id, channel_slug)
);

alter table public.news_sources add column if not exists title text;
alter table public.news_sources add column if not exists last_post_id bigint;
alter table public.news_sources add column if not exists last_checked_at timestamptz;
alter table public.news_sources add column if not exists enabled boolean not null default true;
alter table public.news_sources add column if not exists created_at timestamptz not null default now();
alter table public.news_sources disable row level security;
