create table if not exists public.bot_users (
  telegram_id text primary key,
  microsoft jsonb,
  google jsonb,
  telegram_account jsonb,
  water_rule jsonb,
  bot_state jsonb,
  notification_state jsonb,
  last_sync_at timestamptz
);

alter table public.bot_users add column if not exists google jsonb;
alter table public.bot_users add column if not exists telegram_account jsonb;
alter table public.bot_users add column if not exists bot_state jsonb;
alter table public.bot_users add column if not exists notification_state jsonb;
alter table public.bot_users disable row level security;

create table if not exists public.news_sources (
  id bigint generated by default as identity primary key,
  telegram_id text not null references public.bot_users (telegram_id) on delete cascade,
  url text not null,
  channel_slug text not null,
  title text,
  last_post_id bigint,
  last_checked_at timestamptz,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  unique (telegram_id, channel_slug)
);

alter table public.news_sources add column if not exists title text;
alter table public.news_sources add column if not exists last_post_id bigint;
alter table public.news_sources add column if not exists last_checked_at timestamptz;
alter table public.news_sources add column if not exists enabled boolean not null default true;
alter table public.news_sources add column if not exists created_at timestamptz not null default now();
alter table public.news_sources disable row level security;

create table if not exists public.water_incident_geocodes (
  address_key text primary key,
  city text,
  address_text text not null,
  lat double precision,
  lon double precision,
  provider text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.water_incident_geocodes add column if not exists city text;
alter table public.water_incident_geocodes add column if not exists address_text text;
alter table public.water_incident_geocodes add column if not exists lat double precision;
alter table public.water_incident_geocodes add column if not exists lon double precision;
alter table public.water_incident_geocodes add column if not exists provider text;
alter table public.water_incident_geocodes disable row level security;

create table if not exists public.water_incidents (
  id bigint generated by default as identity primary key,
  telegram_id text not null references public.bot_users (telegram_id) on delete cascade,
  fingerprint text not null unique,
  source_title text,
  source_url text,
  source_channel_slug text,
  external_message_id text,
  raw_text text not null,
  excerpt text,
  kind text not null,
  state text not null,
  city text,
  street text,
  house text,
  address_text text,
  lat double precision,
  lon double precision,
  reported_at timestamptz,
  geocoded_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.water_incidents add column if not exists source_title text;
alter table public.water_incidents add column if not exists source_url text;
alter table public.water_incidents add column if not exists source_channel_slug text;
alter table public.water_incidents add column if not exists external_message_id text;
alter table public.water_incidents add column if not exists raw_text text;
alter table public.water_incidents add column if not exists excerpt text;
alter table public.water_incidents add column if not exists kind text;
alter table public.water_incidents add column if not exists state text;
alter table public.water_incidents add column if not exists city text;
alter table public.water_incidents add column if not exists street text;
alter table public.water_incidents add column if not exists house text;
alter table public.water_incidents add column if not exists address_text text;
alter table public.water_incidents add column if not exists lat double precision;
alter table public.water_incidents add column if not exists lon double precision;
alter table public.water_incidents add column if not exists reported_at timestamptz;
alter table public.water_incidents add column if not exists geocoded_at timestamptz;
alter table public.water_incidents disable row level security;
